name: Publish package to GitHub Packages
on:
  push:
    branches:
      - '**'
  # release:
  #   types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'corretto'
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.GPG_SECRET_KEY }}") | awk '{gsub(/\\n/,"\n")}1' | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      # - name: Publish package
      #   run: mvn --batch-mode deploy -DskipTests
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
